# Generated by Django 6.0.2 on 2026-02-27 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_sid', models.CharField(db_index=True, help_text='Twilio Call SID', max_length=64, unique=True)),
                ('stream_sid', models.CharField(blank=True, help_text='Twilio Stream SID', max_length=64, null=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer')], default='initiated', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('context_url', models.URLField(blank=True, help_text='External API to fetch caller context from', null=True)),
                ('context_headers', models.JSONField(blank=True, help_text='Headers for the context API call', null=True)),
                ('context_data', models.JSONField(blank=True, help_text='Data fetched from the context API', null=True)),
                ('system_prompt', models.TextField(default='You are a helpful, brief, and friendly AI phone assistant. Always speak conversationally.', help_text='System prompt for the AI during this call')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('call_initiated', 'Call Initiated'), ('call_started', 'Call Started'), ('context_fetched', 'Context Fetched'), ('transcription', 'Transcription'), ('ai_response', 'AI Response'), ('tts_sent', 'TTS Sent'), ('call_ended', 'Call Ended'), ('error', 'Error')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calls.callsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='calls.callsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
